# Generated by Django 3.2.9 on 2022-01-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('listingid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('starting_amount', models.PositiveBigIntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='userid')),
            ],
        ),
        migrations.CreateModel(
            name='winner',
            fields=[
                ('winner_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('listing', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing', verbose_name='listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='winner_user')),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('bid_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bid_amount', models.PositiveBigIntegerField(default=0)),
                ('listing', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing', verbose_name='listingid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userid')),
            ],
        ),
    ]
